CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
;

CRATE TABLE FNO EXISTS products (
    id INT AUTO_INCREMEENT PRIMARY KEY,
    name VARCHAR255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock_quantity INT NOT NULL DEFAULT 0,
    created_at THMESTAMP DEFAULT CURRENT_TIMESTAMP
);
